services:
  server:
    container_name: vkalance_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 2869:2869
    volumes:
      - ./server/documents:/app/static/documents
      - ./server/messages:/app/static/messages
    depends_on:
      - mongodb
    networks:
      - vkalance-net

  mongodb:
    image: mongo
    container_name: vkalance_mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./server/.env
    networks:
      - vkalance-net

  mongo-express:
    image: mongo-express
    container_name: vkalance_mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
    networks:
      - vkalance-net

networks:
  vkalance-net:
    name: vkalance-net
    driver: bridge