services:
  server:
    container_name: vkalance_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:2869:2869"
    volumes:
      - ./server/documents:/app/static/documents
      - ./server/messages:/app/static/messages
    depends_on:
      - mongodb
    networks:
      - vkalance-net

  mongodb:
    image: mongo
    container_name: vkalance_mongo
    command: mongod --quiet --logpath /dev/null
    restart: always
    ports:
      - 27017:27017
    env_file:
      - ./server/.env
    networks:
      - vkalance-net

  mongo-express:
    image: mongo-express
    container_name: vkalance_mongo-express
    restart: always
    ports:
      - "127.0.0.1:8081:8081"
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
    networks:
      - vkalance-net

  client-builder:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: vkabureau-client-builder
    volumes:
      - ./client-files:/client/dist

networks:
  vkalance-net:
    name: vkalance-net
    driver: bridge