server:
  address: :2869

authorizer:
  accessSecretKey: access-secret-key

database:
  connUri: mongodb://admin:admin@mongodb:27017/vkalance?ssl=false&authSource=admin
  databaseName: vkalance

migrations:
  enable: true
  dirUrl: file:///app/migrations